
<GiftScreen>:
    name : "gift_screen"
    MDBoxLayout:
        id : gift_outer_box
        orientation : 'vertical'
        spacing : 5

        ReusableTopBar:
            id: top_bar

        MDScrollView:
            id : scroll_gifts
            effect_cls : "DampedScrollEffect"
            edge_damping : 0
            overscroll : 0
            scroll_type : ['bars','content']

            MDBoxLayout:
                id : gift_layout
                orientation: 'vertical'
                size_hint_y : None
                height:self.minimum_height
                spacing : 10
                padding : 10