
<MarriageHomeScreen>:
    name: "marriage_home"
    MDBoxLayout:
        orientation: 'vertical'
        #size_hint_y : None
        #padding : 20
        spacing: 5
        #adaptive_height: True


        ReusableTopBar:
            id: top_bar

        MDScrollView:
            id : scroll_chats
            scroll_y: 0
            effect_cls : "DampedScrollEffect"
            scroll_type : ['bars','content']

            MDBoxLayout:
                id : marriage_layout
                orientation: 'vertical'
                size_hint_y : None
                height:self.minimum_height

                MDLabel:
                    id : marriage_label
                    text: "Enter Marriage Code"
                    pos_hint: {"center_x": 0.5, "center_y": 0.9}
                    halign: "center"
                    font_style : "H4"

                MDTextField:
                    id: mar_code
                    hint_text: "Marriage Code Must"
                    write_tab: False
                    required: True

                MDRaisedButton:
                    text: "Pick Details"
                    pos_hint: {"center_x": 0.5, "center_y": 0.5}
                    size_hint: 0.5, 0.08
                    on_release:
                        app.root.ids.marriage_home.show_marriage_options(mar_code.text) if mar_code.text != '' else None
                    #md_bg_color: "#2AB7CA"
                    text_color: "white"
                    border_radius: [30, 30, 30, 30]

                MDGridLayout:
                    id: grid_layout
                    cols: 2
                    adaptive_height: True
                    adaptive_width : True
                    spacing: dp(20)
                    padding: dp(10)
                    #row_force_default : True
                    #row_default_height : 180
                    #col_force_default : True
                    #col_default_width : 600
                    size_hint_y : None
                    #size_hint :( 1 ,1 )
                    height:self.minimum_height
                    size_hint_x: 1
                    #width: self.maximum_width
                    pos_hint: {"center_x": 0.5, "center_y": 0.5}